import { Db } from 'mongodb';

export const mongoCollections = {
  tenants: 'tenants',
  members: 'members',
  invites: 'invites',
  setPasswordTokens: 'setPasswordTokens',
  audits: 'audits',
  checklistItems: 'checklistItems',
  findings: 'findings',
  capa: 'capa',
  auditMeetings: 'auditMeetings',
  auditConclusions: 'auditConclusions',
  reportMeta: 'reportMeta',
  changeLog: 'changeLog',
  environmentalAspects: 'environmentalAspects',
  complianceObligations: 'complianceObligations',
  emergencyRecords: 'emergencyRecords',
  interestedParties: 'interestedParties',
  environmentalObjectives: 'environmentalObjectives',
  communicationRecords: 'communicationRecords',
  managementReviews: 'managementReviews',
  risksOpportunities: 'risksOpportunities',
  resourceRecords: 'resourceRecords',
  competenceRecords: 'competenceRecords',
  workers: 'workers',
  sites: 'sites',
  awarenessRecords: 'awarenessRecords',
  documentedInfo: 'documentedInfo',
  performanceMetrics: 'performanceMetrics',
  permits: 'permits',
  incidents: 'incidents',
  hira: 'hira',
  calibration: 'calibration',
  training: 'training',
  suppliers: 'suppliers',
  changes: 'changes',
  operationalControls: 'operationalControls',
  leadership: 'leadership',
  context: 'context',
  interviews: 'interviews',
  envAspects: 'envAspects',
  envObligations: 'envObligations',
  envObjectives: 'envObjectives',
  workerConsultations: 'workerConsultations',
  auditProgrammes: 'auditProgrammes',
  evidence: 'evidence',
  evidenceRequests: 'evidenceRequests',
  evidenceUploadIntents: 'evidenceUploadIntents',
  photoAnalyses: 'photoAnalyses',
  reports: 'reports',
  capaReminders: 'capaReminders',
  backendJobs: 'backendJobs',
  observabilityEvents: 'observabilityEvents',
  // Enterprise auth: tenant SSO (OIDC) config + tenant SCIM provisioning tokens.
  ssoConfigs: 'ssoConfigs',
  provisioningTokens: 'provisioningTokens',
} as const;

export type MongoCollectionName = (typeof mongoCollections)[keyof typeof mongoCollections];

export async function ensureMongoIndexes(db: Db): Promise<void> {
  await Promise.all([
    db.collection(mongoCollections.tenants).createIndex({ id: 1 }, { unique: true }),
    db.collection(mongoCollections.members).createIndex({ tenantId: 1, uid: 1 }, { unique: true }),
    // One account per email address across the platform (provisioning relies on this).
    db.collection(mongoCollections.members).createIndex({ 'profile.email': 1 }, { unique: true }),
    db.collection(mongoCollections.invites).createIndex({ tenantId: 1, email: 1, status: 1 }),
    db.collection(mongoCollections.setPasswordTokens).createIndex({ tokenHash: 1 }, { unique: true }),
    db.collection(mongoCollections.setPasswordTokens).createIndex({ tenantId: 1, uid: 1, purpose: 1 }),
    db.collection(mongoCollections.setPasswordTokens).createIndex({ expiresAt: 1 }),
    db.collection(mongoCollections.audits).createIndex({ tenantId: 1, auditeeId: 1, status: 1 }),
    db.collection(mongoCollections.audits).createIndex({ tenantId: 1, assignedMembers: 1 }),
    db.collection(mongoCollections.checklistItems).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.findings).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.capa).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.capa).createIndex({ tenantId: 1, auditId: 1, findingRef: 1 }),
    db.collection(mongoCollections.auditMeetings).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.auditConclusions).createIndex({ tenantId: 1, auditId: 1 }, { unique: true }),
    db.collection(mongoCollections.reportMeta).createIndex({ tenantId: 1, auditId: 1 }, { unique: true }),
    db.collection(mongoCollections.changeLog).createIndex({ tenantId: 1, auditId: 1, at: -1 }),
    db.collection(mongoCollections.environmentalAspects).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.complianceObligations).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.emergencyRecords).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.interestedParties).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.environmentalObjectives).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.communicationRecords).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.managementReviews).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.risksOpportunities).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.resourceRecords).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.competenceRecords).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.workers).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.sites).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.awarenessRecords).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.documentedInfo).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.performanceMetrics).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.permits).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.incidents).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.hira).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.calibration).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.training).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.suppliers).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.changes).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.operationalControls).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.leadership).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.context).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.interviews).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.envAspects).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.envObligations).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.envObjectives).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.workerConsultations).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.auditProgrammes).createIndex({ tenantId: 1 }, { unique: true }),
    db.collection(mongoCollections.evidence).createIndex({ tenantId: 1, auditId: 1, createdBy: 1, timestamp: -1 }),
    db.collection(mongoCollections.evidenceRequests).createIndex({ tenantId: 1, auditId: 1, id: 1 }, { unique: true }),
    db.collection(mongoCollections.evidenceUploadIntents).createIndex({ idempotencyKey: 1 }, { unique: true }),
    db.collection(mongoCollections.evidenceUploadIntents).createIndex({ tenantId: 1, auditId: 1, createdByUid: 1 }),
    db.collection(mongoCollections.photoAnalyses).createIndex({ tenantId: 1, auditId: 1, status: 1 }),
    db.collection(mongoCollections.reports).createIndex({ tenantId: 1, auditId: 1, version: -1 }),
    db.collection(mongoCollections.capaReminders).createIndex({ tenantId: 1, auditId: 1, sendAt: 1, status: 1 }),
    db.collection(mongoCollections.backendJobs).createIndex({ idempotencyKey: 1 }, { unique: true }),
    db.collection(mongoCollections.backendJobs).createIndex({ tenantId: 1, callableName: 1, status: 1, createdAt: -1 }),
    db.collection(mongoCollections.observabilityEvents).createIndex({ tenantId: 1, auditId: 1, occurredAt: -1 }),
    db.collection(mongoCollections.ssoConfigs).createIndex({ tenantId: 1 }, { unique: true }),
    db.collection(mongoCollections.provisioningTokens).createIndex({ tokenHash: 1 }, { unique: true }),
    db.collection(mongoCollections.provisioningTokens).createIndex({ tenantId: 1 }),
  ]);
}
